### ISSUE TITLE
inline_svg wotn work for mask-image

### ISSUE THREAD

**Issue by Zmokizmoghi** [franzheidl/sass-inline-svg#11]
Hi!
Problem: `inline_svg` wont replace itself when used with `mask-image` property.
Workaround: Add `#not-existing-element{background: inline_svg('logo.svg');};` to your `application.sass` and `inline_svg` works just fine, even with `mask-image`.
Perhaps there is a bug somewhere initialization.
Thanks.

**Comment by franzheidl** [comment]
Hi,

that's weird, as sass-inline-svg generally does not care what property called it 🤔. Could you post the exact input and output you're getting?

**Comment by Zmokizmoghi** [comment]
Hello.
Strange, but i can't reproduce it anymore.
Probably it was some misconfiguration or just my f#ckup 😓 
Sorry for bothering you, and thanks for this great gem!

**Comment by franzheidl** [comment]
Happy to hear that, thank you! 👍
